<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\WorkspaveApiController;
use App\Http\Controllers\Api\BackupController;


Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});


Route::prefix('google-workspace')->group(function () {
    
    Route::get('/health', [WorkspaveApiController::class, 'healthCheck'])->name('google-workspace.health');
    Route::prefix('users')->group(function () {
        Route::post('/', [WorkspaveApiController::class, 'createUser'])->name('google-workspace.users.create');
        Route::post('/bulk', [WorkspaveApiController::class, 'createBulkUsers'])->name('google-workspace.users.bulk-create');
        Route::get('/{email}', [WorkspaveApiController::class, 'getUser'])->name('google-workspace.users.show')->where('email', '.*'); 
        Route::put('/{email}', [WorkspaveApiController::class, 'updateUser'])->name('google-workspace.users.update')->where('email', '.*');           
        Route::patch('/{email}', [WorkspaveApiController::class, 'updateUser'])->name('google-workspace.users.patch')->where('email', '.*');
        Route::delete('/{email}', [WorkspaveApiController::class, 'deleteUser'])->name('google-workspace.users.delete')->where('email', '.*');
    });
});



Route::prefix('backup')->group(function () {
    // Create and upload backup
    // POST /api/backup/create
    Route::post('/create', [BackupController::class, 'createAndUpload']);
    
    // Get backup history
    // GET /api/backup/history?user_id=1
    Route::get('/history', [BackupController::class, 'history']);
});













// /*
//  *  This API can automatically create a Google Workspace user whenever a user is created in LAMS system. 

//  *  Key Requirements for Integration

//  *  LAMS system needs to:
//  *  trigger an API Call to the Google Workspace endpoint (POST /google-workspace/users) after saving the user to LAMS's database.
//  *  In LAMS user creation workflow (e.g., the controller or service that handles user registration), after saving the user to the database, 
//  *  trigger this API call.

//  *  Supply the Required Data:
//  *  "first_name" "last_name" "username" (the auto-generated ussername will be email , e.g., johndoe.department@leads.edu.pk).

//  *  The Google Workspace API requires the following fields for user creation:
//  *  {
//  *     "first_name": "John",
//  *     "last_name": "Doe",
//  *     "username": "john.doe.department@leads.edu.pk"
//  *  }


//  *  Key Benefits of This Integration:
//  *  Automatic User Creation: No manual steps required to create Google Workspace accounts.
//  *  Consistent Data: The username is generated by LAMS and used directly in Google Workspace.
//  *  Error Handling: The API returns clear error messages (e.g., duplicate user, invalid format) for troubleshooting.
//  *  Audit Logs: The Google API logs all creation attempts, and LAMS can log failures.
//  */
